//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::customers::Entity as Customers;
pub use super::employees::Entity as Employees;
pub use super::orders::Entity as Orders;
pub use super::ordersarchive::Entity as Ordersarchive;
pub use super::products::Entity as Products;
